### ISSUE TITLE
automod2 imagelimit isn't working in botspam mods channel on comm server

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/misc-cogs#202]
![image](https://user-images.githubusercontent.com/18037011/123526903-9b16b480-d6a0-11eb-8fba-5da6245af624.png)

```
Exception in command 'automod2 imagelimit'
Traceback (most recent call last):
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/bot/.local/share/Red-DiscordBot/data/tsubaki_prod/cogs/CogManager/cogs/automod2/automod2.py", line 287, in imagelimit
    self.settings.setImageLimit(ctx.guild.id, channel or ctx.channel.id, limit)
  File "/home/bot/.local/share/Red-DiscordBot/data/tsubaki_prod/cogs/CogManager/cogs/automod2/automod2.py", line 815, in setImageLimit
    self.save_settings()
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/tsutils/cog_settings.py", line 40, in save_settings
    write_json_file(self.file_path, self.bot_settings)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/tsutils/json_utils.py", line 29, in write_json_file
    json.dump(js_data, f, indent=4)
  File "/usr/local/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 376, in _iterencode_dict
    raise TypeError(f'keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not TextChannel
```

**Comment by RheingoldRiver** [comment]
this is somehow fixed now
